### ISSUE TITLE
undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by jeannot49** [taylorthurlow/panda-motd#29]
### Bug description
Hello,
I'm facing a little issue with the installation.
I have installed Ruby2.3 on my fresh Debian 9 and did the "sudo gem install panda-motd" command. Then I wrote panda-motd ~/.config/panda-motd.yaml and I have an error.

### Expected behavior
Generation of a YAML file containing options to customize panda-motd.

### Log file
/var/lib/gems/2.3.0/gems/panda-motd-0.0.11/lib/panda_motd/config.rb:50:in `load_config': undefined method `[]' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.3.0/gems/panda-motd-0.0.11/lib/panda_motd/config.rb:13:in `initialize'
        from /var/lib/gems/2.3.0/gems/panda-motd-0.0.11/lib/panda_motd/motd.rb:7:in `new'
        from /var/lib/gems/2.3.0/gems/panda-motd-0.0.11/lib/panda_motd/motd.rb:7:in `initialize'
        from /var/lib/gems/2.3.0/gems/panda-motd-0.0.11/lib/panda_motd.rb:9:in `new'
        from /var/lib/gems/2.3.0/gems/panda-motd-0.0.11/lib/panda_motd.rb:9:in `new_motd'
        from /var/lib/gems/2.3.0/gems/panda-motd-0.0.11/bin/panda-motd:5:in `<top (required)>'
        from /usr/local/bin/panda-motd:22:in `load'
        from /usr/local/bin/panda-motd:22:in `<main>'

### OS Information
 - OS: Debian 9.7 - 64 bits -- bash 4.4.12

**Comment by taylorthurlow** [comment]
@jeannot49 You fix the problem OK? Let me know what the problem was and how you fixed it.

**Comment by jeannot49** [comment]
Hello,
Yeah sorry it was my fault.
The error message appeared when I 
I read your commit list just after, then I have installed Ruby2.6. The problem was that I ran the 2.3.

Thanks !

**Comment by taylorthurlow** [comment]
panda-motd should work with Ruby 2.3 or newer, interesting.
